version: "3.8"
services:

  # PHP service
  app:
    build: ./server/docker/php
    container_name: micro-php
    working_dir: /var/www/
    volumes:
      - ./server/:/var/www
    networks:
      - micro-network

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: micro-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./server/.env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - micro-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: micro-nginx
    ports:
      - "80:80"
    volumes:
      - ./server/:/var/www
      - ./server/docker/nginx/:/etc/nginx/conf.d/
      - ./server/var/log/nginx/:/var/log/nginx/
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
