version: "3.8"
services:

  # PHP service
  backend:
    build: ./docker/php
    container_name: backend-clean-api
    working_dir: /var/www/backend
    volumes:
      - ./backend/:/var/www/backend
    networks:
      - clean-api-network

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./docker/node/Dockerfile
  #     target: build
  #   container_name: frontend-clean-api
  #   volumes:
  #     - ./frontend/:/app
  #     - ./frontend/node_modules/:/app/node_modules
  #   networks:
  #     - clean-api-network

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: mysql-clean-api
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - clean-api-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx-clean-api
    ports:
      - "80:80"
    volumes:
      - ./backend/:/var/www/backend
      # - ./frontend/dist/:/var/www/frontend
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./backend/var/log/nginx/:/var/log/nginx/
      # - ./frontend/log/vue/:/var/log/vue/
    networks:
      - clean-api-network

networks:
  clean-api-network:
    driver: bridge

volumes:
  db-data:
